import { PRODUCTS, GROWTH_DATA } from '@/lib/data'

const GROWTH_FILES = ['GROWTH_GUIDE.md', 'SEO_CHECKLIST.md', 'SOCIAL_MEDIA_PLAN.md', 'PRODUCT_LAUNCH_PLAN.md', 'KPI_DASHBOARD.md']

function seoGradeColor(grade: string) {
  if (grade === 'A' || grade === 'B') return 'text-emerald-400'
  if (grade === 'C')                  return 'text-amber-400'
  return 'text-red-400'
}

export default function GrowthDashboard() {
  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white">Growth Dashboard</h1>
        <p className="text-slate-400 text-sm mt-1">SEO · Analytics · Social · Launch readiness</p>
      </div>

      {/* Analytics alert */}
      <div className="flex items-start gap-3 bg-amber-400/5 border border-amber-400/30 rounded-xl p-4 mb-8">
        <span className="text-amber-400 text-lg mt-0.5">⚠</span>
        <div>
          <div className="font-semibold text-amber-400">Analytics Not Configured</div>
          <div className="text-sm text-slate-400 mt-1">
            Zero analytics on all 3 live products. Cannot measure traffic, retention, or conversion. Set up GA4 or Plausible before running any paid promotion or Product Hunt launch.
          </div>
        </div>
      </div>

      {/* SEO Audit table */}
      <div className="bg-[#111827] border border-[#1f2937] rounded-xl overflow-hidden mb-6">
        <div className="px-6 py-4 border-b border-[#1f2937]">
          <h2 className="font-semibold text-white">SEO Audit Results</h2>
          <p className="text-xs text-slate-400 mt-1">Live URL audit · Generated by Growth Agent · {new Date().toISOString().slice(0, 10)}</p>
        </div>
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-[#1f2937]">
              <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase">Product</th>
              <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase">Score</th>
              <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase hidden sm:table-cell">robots.txt</th>
              <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase hidden sm:table-cell">sitemap.xml</th>
              <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase hidden md:table-cell">Top Gap</th>
            </tr>
          </thead>
          <tbody>
            {GROWTH_DATA.map((g, i) => {
              const product = PRODUCTS.find(p => p.id === g.productId)
              return (
                <tr key={g.productId} className={i < GROWTH_DATA.length - 1 ? 'border-b border-[#1f2937]' : ''}>
                  <td className="px-6 py-4 font-medium text-white">{product?.name}</td>
                  <td className="px-6 py-4">
                    <span className={`font-bold ${seoGradeColor(g.grade)}`}>{g.seoScore}</span>
                    <span className={`text-xs ml-1.5 font-medium ${seoGradeColor(g.grade)}`}>({g.grade})</span>
                  </td>
                  <td className="px-6 py-4 hidden sm:table-cell">
                    <span className={g.hasRobots ? 'text-emerald-400' : 'text-red-400'}>{g.hasRobots ? '✓' : '✗'}</span>
                  </td>
                  <td className="px-6 py-4 hidden sm:table-cell">
                    <span className={g.hasSitemap ? 'text-emerald-400' : 'text-red-400'}>{g.hasSitemap ? '✓' : '✗'}</span>
                  </td>
                  <td className="px-6 py-4 text-xs text-slate-400 hidden md:table-cell">{g.topGap}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Growth packages */}
      <div className="bg-[#111827] border border-[#1f2937] rounded-xl overflow-hidden mb-6">
        <div className="px-6 py-4 border-b border-[#1f2937]">
          <h2 className="font-semibold text-white">Growth Packages</h2>
          <p className="text-xs text-slate-400 mt-1">5 files generated per product by Growth Agent</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-[#1f2937]">
                <th className="text-left px-6 py-3 text-xs font-medium text-slate-400 uppercase">Product</th>
                {GROWTH_FILES.map(f => (
                  <th key={f} className="text-left px-4 py-3 text-xs font-medium text-slate-400 uppercase whitespace-nowrap">{f.replace('.md','')}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {PRODUCTS.map((p, i) => (
                <tr key={p.id} className={i < PRODUCTS.length - 1 ? 'border-b border-[#1f2937]' : ''}>
                  <td className="px-6 py-4 font-medium text-white">{p.name}</td>
                  {GROWTH_FILES.map(f => (
                    <td key={f} className="px-4 py-4">
                      <span className="text-emerald-400">✓</span>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Launch readiness */}
      <div className="bg-[#111827] border border-[#1f2937] rounded-xl p-6">
        <h2 className="font-semibold text-white mb-4">Launch Readiness</h2>
        <div className="space-y-4">
          {GROWTH_DATA.map(g => {
            const product = PRODUCTS.find(p => p.id === g.productId)
            const channels = [
              { label: 'Reddit', done: g.launchStatus.reddit },
              { label: 'Hacker News', done: g.launchStatus.hackerNews },
              { label: 'Product Hunt', done: g.launchStatus.productHunt },
              { label: 'Dev.to', done: g.launchStatus.devTo },
              { label: 'Analytics', done: g.analyticsConfigured },
            ]
            return (
              <div key={g.productId} className="bg-[#0f172a] border border-slate-800 rounded-lg p-4">
                <div className="font-medium text-white mb-3">{product?.name}</div>
                <div className="flex flex-wrap gap-2">
                  {channels.map(c => (
                    <span key={c.label} className={`text-xs border rounded px-2 py-1 ${c.done ? 'text-emerald-400 border-emerald-400/30 bg-emerald-400/5' : 'text-slate-500 border-slate-700'}`}>
                      {c.done ? '✓' : '○'} {c.label}
                    </span>
                  ))}
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
